### ISSUE TITLE
faucet.metamask.io - Error: 500

### ISSUE THREAD

**Issue by firke** [MetaMask/eth-faucet#35]
Currently getting error 500 on the faucet on different networks - tried Ropsten and Kovan, seems to be the same. When requesting funds, outputs the following at the bottom:

`Error: 500 {"error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Too Many Requests\",\"data\":{\"originalError\":{}},\"stack\":\"Error: Too Many Requests\\n at eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:52:23)\\n at Request.eval [as _callback] (/www/node_modules/web3-provider-engine/subproviders/rpc.js:54:11)\\n at Request.self.callback (/www/node_modules/request/request.js:186:22)\\n at Request.emit (events.js:315:20)\\n at Request.eval (/www/node_modules/request/request.js:1155:10)\\n at Request.emit (events.js:315:20)\\n at IncomingMessage.eval (/www/node_modules/request/request.js:1077:12)\\n at Object.onceWrapper (events.js:421:28)\\n at IncomingMessage.emit (events.js:327:22)\\n at endReadableNT (internal/streams/readable.js:1327:12)\"}}'"}`

**Comment by Aniket-Engg** [comment]
I get 504: 
```
/www/node_modules/cross-fetch/dist/browser-ponyfill.js:521 POST https://faucet.metamask.io/v0/request 504
```

**Comment by oneknucklehead** [comment]
any updates on this error yet?
