### ISSUE TITLE
Error#1: LavaMoat - required package not in whitelist: package "lavamoat-tofu" requested "@babel\parser" as "@babel/parser"

### ISSUE THREAD

**Issue by chengpeiquan** [MetaMask/eth-faucet#47]
I cloned this repository locally, but it doesn't work.

Run `yarn setup`, It's OK:

```bash
PS E:\Project\eth\eth-faucet> yarn setup
yarn run v1.22.10
$ yarn install && patch-package && allow-scripts
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
patch-package 6.4.7
Applying patches...
acorn@7.4.1 ✔
depd@1.1.2 ✔
esprima@4.0.1 ✔
jsesc@2.5.2 ✔
running lifecycle scripts for event "preinstall"
running lifecycle scripts for event "install"
- keccak
- secp256k1
running lifecycle scripts for event "postinstall"
running lifecycle scripts for top level package
Done in 2.24s.
```

Run `yarn build`, an error occurred:

```bash
PS E:\Project\eth\eth-faucet> yarn build
yarn run v1.22.10
$ (cd src/bundler && lavamoat index.js)
(Error#1)
Error#1: LavaMoat - required package not in whitelist: package "lavamoat-tofu" requested "@babel\parser" as "@babel/parser"
  at requireRelative (LavaMoat/core/kernel:518:15)
  at requireRelativeWithContext (LavaMoat/core/kernel:470:16)
  at Object.eval (E:\Project\eth\eth-faucet\node_modules\lavamoat-tofu\src\index.js:2:19)
  at internalRequire (LavaMoat/core/kernel:457:25)
  at requireRelative (LavaMoat/core/kernel:498:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:470:16)
  at Object.eval (E:\Project\eth\eth-faucet\node_modules\lavamoat-core\src\generateConfig.js:13:5)
  at internalRequire (LavaMoat/core/kernel:457:25)
  at requireRelative (LavaMoat/core/kernel:498:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:470:16)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS E:\Project\eth\eth-faucet>
```

How should this situation be handled?

**Comment by duanescarlett** [comment]
I am having the same type of error, is there anyone out there that can help with this?
